# Generated by Django 4.0.5 on 2022-06-11 08:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hours',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='staff',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
