# Generated by Django 4.0.5 on 2022-06-12 14:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shift',
            name='workdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('start_time', 'end_time', 'workdays')},
        ),
    ]
