# Generated by Django 4.0.5 on 2022-06-12 15:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_shift_unique_together_shift_staff_needed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shift',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('start_time', 'end_time', 'weekdays')},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='workdays',
        ),
    ]
