# Generated by Django 4.0.5 on 2022-06-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('shift', '0004_alter_shift_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='location',
            field=models.ManyToManyField(to='location.location'),
        ),
    ]
