# Generated by Django 4.0.5 on 2022-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('day', '0003_alter_day_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='June', max_length=80)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('days', models.ManyToManyField(null=True, to='day.day')),
            ],
        ),
    ]
