# Generated by Django 4.0.5 on 2022-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_alter_day_date'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='day.day'),
        ),
    ]
