# Generated by Django 4.0.5 on 2022-06-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
                ('shifts', models.ManyToManyField(blank=True, to='schedule.schedule')),
            ],
        ),
    ]
