# Generated by Django 4.0.5 on 2022-06-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('shift', '0001_initial'),
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='day',
            name='shifts',
            field=models.ManyToManyField(blank=True, to='shift.shift'),
        ),
    ]
