# Generated by Django 4.0.5 on 2022-06-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('start_date', 'end_date')},
        ),
    ]
