# Generated by Django 4.0.5 on 2022-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_alter_shift_unique_together'),
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='day',
            name='shifts',
            field=models.ManyToManyField(blank=True, to='shift.shift'),
        ),
    ]
